export const endpoints = {
  userProfile: "/api/user/profile",
  resetUser: "/api/user/reset",
  trainingProfile: "/api/onboarding/training-profile",
  currentTrainingPlan: "/api/training-plans/current",
  todayWorkout: "/api/workout/today",
  generateTodayWorkout: "/api/workout/today/generate",
  updateTodayExercises: "/api/workout/today/exercises",
  adjustWorkoutIntensity: "/api/workout/today/intensity",
  workoutSessions: "/api/workout-sessions",
  workoutSessionHistory: "/api/workout-sessions",
  currentWorkoutSession: "/api/workout-sessions/current",
  endCurrentWorkoutSession: "/api/workout-sessions/current/end",
  updateCurrentExercise: "/api/workout-sessions/current/exercise",
  scanEquipment: "/api/equipment/scan",
  latestScanResult: "/api/equipment/scans/latest",
  scanFeedback: "/api/equipment/scan-feedback",
  exercises: "/api/exercises",
  exerciseDetail: (exerciseId: string) => `/api/exercises/${exerciseId}`,
  addExercise: "/api/workout/add-exercise",
  replaceExercise: "/api/workout/replace-exercise",
  parseWorkoutLog: "/api/workout/log/parse",
  saveWorkoutLog: "/api/workout/log",
  workoutRecords: "/api/workout/log",
  workoutInsights: "/api/workout/insights",
  analyticsCalendar: "/api/analytics/calendar",
  analyticsOverview: "/api/analytics/overview",
  assistantMessages: "/api/assistant/messages",
  mediaUpload: "/api/media/upload",
  analyzeBodyPhoto: "/api/body-photo/analyze",
  latestBodyPhotoAnalysis: "/api/body-photo/analyses/latest"
} as const;
