import type { ScanScenario } from "../types/api";
import { mockApi } from "./mockApi";
import { realApi } from "./realApi";

const useRealApi = import.meta.env.VITE_USE_REAL_API === "true";

export const tieziApi = useRealApi ? realApi : mockApi;

export type { ScanScenario };
export const getUserProfile = tieziApi.getUserProfile;
export const updateUserProfile = tieziApi.updateUserProfile;
export const resetUserData = tieziApi.resetUserData;
export const saveTrainingProfile = tieziApi.saveTrainingProfile;
export const getCurrentTrainingPlan = tieziApi.getCurrentTrainingPlan;
export const getTodayWorkout = tieziApi.getTodayWorkout;
export const generateTodayWorkout = tieziApi.generateTodayWorkout;
export const updateTodayExercises = tieziApi.updateTodayExercises;
export const adjustWorkoutIntensity = tieziApi.adjustWorkoutIntensity;
export const createWorkoutSession = tieziApi.createWorkoutSession;
export const getCurrentWorkoutSession = tieziApi.getCurrentWorkoutSession;
export const getWorkoutSessions = tieziApi.getWorkoutSessions;
export const endCurrentWorkoutSession = tieziApi.endCurrentWorkoutSession;
export const updateCurrentExercise = tieziApi.updateCurrentExercise;
export const getExercises = tieziApi.getExercises;
export const getExerciseDetail = tieziApi.getExerciseDetail;
export const scanEquipment = tieziApi.scanEquipment;
export const getLatestScanResult = tieziApi.getLatestScanResult;
export const submitScanFeedback = tieziApi.submitScanFeedback;
export const addExerciseToWorkout = tieziApi.addExerciseToWorkout;
export const replaceExerciseInWorkout = tieziApi.replaceExerciseInWorkout;
export const parseWorkoutLog = tieziApi.parseWorkoutLog;
export const saveWorkoutLog = tieziApi.saveWorkoutLog;
export const getWorkoutRecords = tieziApi.getWorkoutRecords;
export const getTrainingInsights = tieziApi.getTrainingInsights;
export const getAnalyticsCalendar = tieziApi.getAnalyticsCalendar;
export const getAnalyticsOverview = tieziApi.getAnalyticsOverview;
export const sendAssistantMessage = tieziApi.sendAssistantMessage;
export const getAssistantMessages = tieziApi.getAssistantMessages;
export const uploadMedia = tieziApi.uploadMedia;
export const analyzeBodyPhoto = tieziApi.analyzeBodyPhoto;
export const getLatestBodyPhotoAnalysis = tieziApi.getLatestBodyPhotoAnalysis;
